name: Deploy Deno Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            # 최초 실행 시 저장소가 없다면 클론
            if [ ! -d "${{ secrets.APP_DIR }}/.git" ]; then
              mkdir -p ${{ secrets.APP_DIR }}
              git clone https://github.com/jeongbaebang/test-ubuntu.git ${{ secrets.APP_DIR }}
            fi
            
            # .env 파일 생성
            cd ${{ secrets.APP_DIR }}
            echo "PORT=${{ secrets.APP_PORT }}" > .env
            
            # 코드 업데이트 및 애플리케이션 재시작
            git fetch --all
            git reset --hard origin/main
            deno cache --reload app.ts
            pm2 restart deno-app || pm2 start app.ts --interpreter="deno" --interpreter-args="run --allow-net --allow-env --allow-read" --name "deno-app"

