name: Deploy Deno Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            set -e
            APP_DIR="${{ secrets.APP_DIR }}"

            # 저장소 초기화 (최초 1회 실행)
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/jeongbaebang/test-ubuntu.git $APP_DIR
            fi

            cd $APP_DIR
            git fetch --all
            git reset --hard origin/main

            # .env 파일 생성 및 권한 설정
            echo "PORT=${{ secrets.APP_PORT }}" > .env

            # 환경 변수 설정
            export DENO_INSTALL="$HOME/.deno"
            export PATH="$DENO_INSTALL/bin:$PATH"

            deno cache --reload app.ts

            # PM2 프로세스 관리
            pm2 restart deno-app --update-env || pm2 start app.ts --interpreter="deno" --interpreter-args="run --allow-net --allow-env --allow-read" --name "deno-app"

            pm2 save
