name: Deploy Deno Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno cache --reload app.ts

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            # Git 저장소 설정 및 코드 업데이트
            if [ ! -d "${{ secrets.APP_DIR }}/.git" ]; then
              cd ${{ secrets.APP_DIR }}
              git init
              git remote add origin https://github.com/jeongbaebang/test-ubuntu.git
              git fetch
            fi

            cd ${{ secrets.APP_DIR }}
            git fetch --all
            git reset --hard origin/main

            # .env 파일 생성 및 권한 설정
            echo "PORT=${{ secrets.APP_PORT }}" > .env

            # 애플리케이션 재시작
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
             
            pm2 restart deno-app || pm2 start app.ts --interpreter="deno" --interpreter-args="run --allow-net --allow-env --allow-read" --name "deno-app"
